<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FLPTech.Blog.Domain.Application\FLPTech.Blog.Domain.Application.csproj" />
    <ProjectReference Include="..\FLPTech.Blog.Domain\FLPTech.Blog.Domain.csproj" />
    <ProjectReference Include="..\FLPTech.Blog.Infraestructure\FLPTech.Blog.Infraestructure.csproj" />
    <ProjectReference Include="..\FLPTech.Blog.ServiceDefaults\FLPTech.Blog.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
